top_srcdir   = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38
top_builddir = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38
srcdir       = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38/modules/arch/unix
builddir     = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38/modules/arch/unix
VPATH        = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38/modules/arch/unix

include $(top_srcdir)/build/special.mk

