top_srcdir   = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38
top_builddir = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38
srcdir       = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38/modules/examples
builddir     = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38/modules/examples
VPATH        = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38/modules/examples
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
