top_srcdir   = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38
top_builddir = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38
srcdir       = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38/modules
builddir     = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38/modules
VPATH        = /Users/zhengxiangyang/work/fjt/fjt_xp/buildScripts/fjtbuild/buildtemp/httpd-2.4.38/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

